


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     TextTransform Packages/com.careboo.blinq/CareBoo.Blinq/ValueSequence/ValueSequence.Sum.tt
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Unity.Mathematics;
using CareBoo.Burst.Delegates;

namespace CareBoo.Blinq
{
    public static partial class Sequence
    {

        public static int Sum<TSource>(
            this ValueSequence<int, TSource> source
            )
            where TSource : struct, ISequence<int>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int2 Sum<TSource>(
            this ValueSequence<int2, TSource> source
            )
            where TSource : struct, ISequence<int2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int2x2 Sum<TSource>(
            this ValueSequence<int2x2, TSource> source
            )
            where TSource : struct, ISequence<int2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int2x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int2x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int2x3 Sum<TSource>(
            this ValueSequence<int2x3, TSource> source
            )
            where TSource : struct, ISequence<int2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int2x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int2x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int2x4 Sum<TSource>(
            this ValueSequence<int2x4, TSource> source
            )
            where TSource : struct, ISequence<int2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int2x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int2x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int2x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int3 Sum<TSource>(
            this ValueSequence<int3, TSource> source
            )
            where TSource : struct, ISequence<int3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int3x2 Sum<TSource>(
            this ValueSequence<int3x2, TSource> source
            )
            where TSource : struct, ISequence<int3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int3x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int3x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int3x3 Sum<TSource>(
            this ValueSequence<int3x3, TSource> source
            )
            where TSource : struct, ISequence<int3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int3x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int3x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int3x4 Sum<TSource>(
            this ValueSequence<int3x4, TSource> source
            )
            where TSource : struct, ISequence<int3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int3x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int3x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int3x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int4 Sum<TSource>(
            this ValueSequence<int4, TSource> source
            )
            where TSource : struct, ISequence<int4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int4x2 Sum<TSource>(
            this ValueSequence<int4x2, TSource> source
            )
            where TSource : struct, ISequence<int4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int4x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int4x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int4x3 Sum<TSource>(
            this ValueSequence<int4x3, TSource> source
            )
            where TSource : struct, ISequence<int4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int4x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int4x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static int4x4 Sum<TSource>(
            this ValueSequence<int4x4, TSource> source
            )
            where TSource : struct, ISequence<int4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static int4x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, int4x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                int4x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint Sum<TSource>(
            this ValueSequence<uint, TSource> source
            )
            where TSource : struct, ISequence<uint>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint2 Sum<TSource>(
            this ValueSequence<uint2, TSource> source
            )
            where TSource : struct, ISequence<uint2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint2x2 Sum<TSource>(
            this ValueSequence<uint2x2, TSource> source
            )
            where TSource : struct, ISequence<uint2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint2x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint2x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint2x3 Sum<TSource>(
            this ValueSequence<uint2x3, TSource> source
            )
            where TSource : struct, ISequence<uint2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint2x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint2x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint2x4 Sum<TSource>(
            this ValueSequence<uint2x4, TSource> source
            )
            where TSource : struct, ISequence<uint2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint2x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint2x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint2x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint3 Sum<TSource>(
            this ValueSequence<uint3, TSource> source
            )
            where TSource : struct, ISequence<uint3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint3x2 Sum<TSource>(
            this ValueSequence<uint3x2, TSource> source
            )
            where TSource : struct, ISequence<uint3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint3x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint3x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint3x3 Sum<TSource>(
            this ValueSequence<uint3x3, TSource> source
            )
            where TSource : struct, ISequence<uint3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint3x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint3x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint3x4 Sum<TSource>(
            this ValueSequence<uint3x4, TSource> source
            )
            where TSource : struct, ISequence<uint3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint3x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint3x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint3x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint4 Sum<TSource>(
            this ValueSequence<uint4, TSource> source
            )
            where TSource : struct, ISequence<uint4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint4x2 Sum<TSource>(
            this ValueSequence<uint4x2, TSource> source
            )
            where TSource : struct, ISequence<uint4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint4x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint4x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint4x3 Sum<TSource>(
            this ValueSequence<uint4x3, TSource> source
            )
            where TSource : struct, ISequence<uint4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint4x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint4x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static uint4x4 Sum<TSource>(
            this ValueSequence<uint4x4, TSource> source
            )
            where TSource : struct, ISequence<uint4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static uint4x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, uint4x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                uint4x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float Sum<TSource>(
            this ValueSequence<float, TSource> source
            )
            where TSource : struct, ISequence<float>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float2 Sum<TSource>(
            this ValueSequence<float2, TSource> source
            )
            where TSource : struct, ISequence<float2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float2x2 Sum<TSource>(
            this ValueSequence<float2x2, TSource> source
            )
            where TSource : struct, ISequence<float2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float2x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float2x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float2x3 Sum<TSource>(
            this ValueSequence<float2x3, TSource> source
            )
            where TSource : struct, ISequence<float2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float2x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float2x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float2x4 Sum<TSource>(
            this ValueSequence<float2x4, TSource> source
            )
            where TSource : struct, ISequence<float2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float2x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float2x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float2x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float3 Sum<TSource>(
            this ValueSequence<float3, TSource> source
            )
            where TSource : struct, ISequence<float3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float3x2 Sum<TSource>(
            this ValueSequence<float3x2, TSource> source
            )
            where TSource : struct, ISequence<float3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float3x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float3x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float3x3 Sum<TSource>(
            this ValueSequence<float3x3, TSource> source
            )
            where TSource : struct, ISequence<float3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float3x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float3x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float3x4 Sum<TSource>(
            this ValueSequence<float3x4, TSource> source
            )
            where TSource : struct, ISequence<float3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float3x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float3x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float3x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float4 Sum<TSource>(
            this ValueSequence<float4, TSource> source
            )
            where TSource : struct, ISequence<float4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float4x2 Sum<TSource>(
            this ValueSequence<float4x2, TSource> source
            )
            where TSource : struct, ISequence<float4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float4x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float4x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float4x3 Sum<TSource>(
            this ValueSequence<float4x3, TSource> source
            )
            where TSource : struct, ISequence<float4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float4x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float4x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static float4x4 Sum<TSource>(
            this ValueSequence<float4x4, TSource> source
            )
            where TSource : struct, ISequence<float4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static float4x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, float4x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                float4x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double Sum<TSource>(
            this ValueSequence<double, TSource> source
            )
            where TSource : struct, ISequence<double>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double2 Sum<TSource>(
            this ValueSequence<double2, TSource> source
            )
            where TSource : struct, ISequence<double2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double2x2 Sum<TSource>(
            this ValueSequence<double2x2, TSource> source
            )
            where TSource : struct, ISequence<double2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double2x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double2x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double2x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double2x3 Sum<TSource>(
            this ValueSequence<double2x3, TSource> source
            )
            where TSource : struct, ISequence<double2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double2x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double2x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double2x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double2x4 Sum<TSource>(
            this ValueSequence<double2x4, TSource> source
            )
            where TSource : struct, ISequence<double2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double2x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double2x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double2x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double2x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double3 Sum<TSource>(
            this ValueSequence<double3, TSource> source
            )
            where TSource : struct, ISequence<double3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double3x2 Sum<TSource>(
            this ValueSequence<double3x2, TSource> source
            )
            where TSource : struct, ISequence<double3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double3x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double3x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double3x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double3x3 Sum<TSource>(
            this ValueSequence<double3x3, TSource> source
            )
            where TSource : struct, ISequence<double3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double3x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double3x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double3x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double3x4 Sum<TSource>(
            this ValueSequence<double3x4, TSource> source
            )
            where TSource : struct, ISequence<double3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double3x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double3x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double3x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double3x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double4 Sum<TSource>(
            this ValueSequence<double4, TSource> source
            )
            where TSource : struct, ISequence<double4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double4x2 Sum<TSource>(
            this ValueSequence<double4x2, TSource> source
            )
            where TSource : struct, ISequence<double4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4x2 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double4x2 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double4x2>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double4x2>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4x2 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double4x3 Sum<TSource>(
            this ValueSequence<double4x3, TSource> source
            )
            where TSource : struct, ISequence<double4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4x3 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double4x3 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double4x3>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double4x3>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4x3 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


        public static double4x4 Sum<TSource>(
            this ValueSequence<double4x4, TSource> source
            )
            where TSource : struct, ISequence<double4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4x4 sum = srcList[0];
                for (var i = 1; i < srcList.Length; i++)
                    sum += srcList[i];
                return sum;
            }
        }

        public static double4x4 Sum<T, TSource, TSelector>(
            this ValueSequence<T, TSource> source,
            ValueFunc<T, double4x4>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double4x4>
        {
            using (var srcList = source.Execute())
            {
                if (srcList.Length == 0) throw Error.NoElements();
                double4x4 sum = selector.Invoke(srcList[0]);
                for (var i = 1; i < srcList.Length; i++)
                    sum += selector.Invoke(srcList[i]);
                return sum;
            }
        }


    }
}
