


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     TextTransform Packages/com.careboo.blinq/CareBoo.Blinq/ValueSequence/ValueSequence.Sum.tt
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CareBoo.Burst.Delegates;
using Unity.Collections;

namespace CareBoo.Blinq
{
    public static partial class Sequence
    {

        public static int Max<TSource>(
            this in ValueSequence<int, TSource> source
            )
            where TSource : struct, ISequence<int>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static int Min<TSource>(
            this in ValueSequence<int, TSource> source
            )
            where TSource : struct, ISequence<int>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }

        public static int Max<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, int>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static int Min<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, int>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, int>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }


        public static uint Max<TSource>(
            this in ValueSequence<uint, TSource> source
            )
            where TSource : struct, ISequence<uint>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static uint Min<TSource>(
            this in ValueSequence<uint, TSource> source
            )
            where TSource : struct, ISequence<uint>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }

        public static uint Max<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, uint>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static uint Min<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, uint>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, uint>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }


        public static float Max<TSource>(
            this in ValueSequence<float, TSource> source
            )
            where TSource : struct, ISequence<float>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static float Min<TSource>(
            this in ValueSequence<float, TSource> source
            )
            where TSource : struct, ISequence<float>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }

        public static float Max<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, float>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static float Min<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, float>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, float>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }


        public static double Max<TSource>(
            this in ValueSequence<double, TSource> source
            )
            where TSource : struct, ISequence<double>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static double Min<TSource>(
            this in ValueSequence<double, TSource> source
            )
            where TSource : struct, ISequence<double>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = srcList[0];
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = srcList[i];
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }

        public static double Max<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, double>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var max = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val > max)
                    max = val;
            }
            srcList.Dispose();
            return max;
        }

        public static double Min<T, TSource, TSelector>(
            this in ValueSequence<T, TSource> source,
            in ValueFunc<T, double>.Struct<TSelector> selector
            )
            where T : struct
            where TSource : struct, ISequence<T>
            where TSelector : struct, IFunc<T, double>
        {
            var srcList = source.ToNativeList(Allocator.Temp);
            if (srcList.Length == 0)
            {
                srcList.Dispose();
                throw Error.NoElements();
            }

            var min = selector.Invoke(srcList[0]);
            for (var i = 1; i < srcList.Length; i++)
            {
                var val = selector.Invoke(srcList[i]);
                if (val < min)
                    min = val;
            }
            srcList.Dispose();
            return min;
        }


    }
}
