

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     TextTransform Packages/com.careboo.blinq/CareBoo.Blinq/ValueSequence/ValueSequence.Sum.tt
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Unity.Collections;
using static ValueFuncs;
using static Utils;
using System.Collections;
using NUnit.Framework;
using Linq = System.Linq.Enumerable;
using Blinq = CareBoo.Blinq.Sequence;

internal class AverageTest
{

    internal class Values_int
    {
        public static IEnumerable Values
        {
            get
            {
                yield return new int[0];
                yield return new int[1];
                yield return Linq.ToArray(Linq.Repeat((int)5, 7));
            }
        }
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayAverage_int(
        [ValueSource(typeof(Values_int), nameof(Values_int.Values))] int[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<int>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        var actual = ExceptionAndValue(() => Blinq.Average(srcNativeArray));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayAverageSelector_int(
        [ValueSource(typeof(Values_int), nameof(Values_int.Values))] int[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<int>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<int>().Invoke));
        var actual = ExceptionAndValue(() => Blinq.Average(srcNativeArray, SelectSelf<int>()));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayRunAverage_int(
        [ValueSource(typeof(Values_int), nameof(Values_int.Values))] int[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<int>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.RunAverage(srcNativeArray));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayRunAverageSelector_int(
        [ValueSource(typeof(Values_int), nameof(Values_int.Values))] int[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<int>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<int>().Invoke));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.RunAverage(srcNativeArray, SelectSelf<int>()));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayScheduleAverage_int(
        [ValueSource(typeof(Values_int), nameof(Values_int.Values))] int[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<int>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.ScheduleAverage(srcNativeArray).Complete());
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayScheduleAverageSelector_int(
        [ValueSource(typeof(Values_int), nameof(Values_int.Values))] int[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<int>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<int>().Invoke));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.ScheduleAverage(srcNativeArray, SelectSelf<int>()).Complete());
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }


    internal class Values_float
    {
        public static IEnumerable Values
        {
            get
            {
                yield return new float[0];
                yield return new float[1];
                yield return Linq.ToArray(Linq.Repeat((float)5, 7));
            }
        }
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayAverage_float(
        [ValueSource(typeof(Values_float), nameof(Values_float.Values))] float[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<float>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        var actual = ExceptionAndValue(() => Blinq.Average(srcNativeArray));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayAverageSelector_float(
        [ValueSource(typeof(Values_float), nameof(Values_float.Values))] float[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<float>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<float>().Invoke));
        var actual = ExceptionAndValue(() => Blinq.Average(srcNativeArray, SelectSelf<float>()));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayRunAverage_float(
        [ValueSource(typeof(Values_float), nameof(Values_float.Values))] float[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<float>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.RunAverage(srcNativeArray));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayRunAverageSelector_float(
        [ValueSource(typeof(Values_float), nameof(Values_float.Values))] float[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<float>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<float>().Invoke));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.RunAverage(srcNativeArray, SelectSelf<float>()));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayScheduleAverage_float(
        [ValueSource(typeof(Values_float), nameof(Values_float.Values))] float[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<float>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.ScheduleAverage(srcNativeArray).Complete());
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayScheduleAverageSelector_float(
        [ValueSource(typeof(Values_float), nameof(Values_float.Values))] float[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<float>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<float>().Invoke));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.ScheduleAverage(srcNativeArray, SelectSelf<float>()).Complete());
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }


    internal class Values_double
    {
        public static IEnumerable Values
        {
            get
            {
                yield return new double[0];
                yield return new double[1];
                yield return Linq.ToArray(Linq.Repeat((double)5, 7));
            }
        }
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayAverage_double(
        [ValueSource(typeof(Values_double), nameof(Values_double.Values))] double[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<double>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        var actual = ExceptionAndValue(() => Blinq.Average(srcNativeArray));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayAverageSelector_double(
        [ValueSource(typeof(Values_double), nameof(Values_double.Values))] double[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<double>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<double>().Invoke));
        var actual = ExceptionAndValue(() => Blinq.Average(srcNativeArray, SelectSelf<double>()));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayRunAverage_double(
        [ValueSource(typeof(Values_double), nameof(Values_double.Values))] double[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<double>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.RunAverage(srcNativeArray));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayRunAverageSelector_double(
        [ValueSource(typeof(Values_double), nameof(Values_double.Values))] double[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<double>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<double>().Invoke));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.RunAverage(srcNativeArray, SelectSelf<double>()));
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayScheduleAverage_double(
        [ValueSource(typeof(Values_double), nameof(Values_double.Values))] double[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<double>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.ScheduleAverage(srcNativeArray).Complete());
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }

    [Test, Parallelizable, Timeout(5000)]
    public void BlinqShouldEqualLinqNativeArrayScheduleAverageSelector_double(
        [ValueSource(typeof(Values_double), nameof(Values_double.Values))] double[] sourceArr
        )
    {
        var srcNativeArray = new NativeArray<double>(sourceArr, Allocator.Persistent);
        var expected = ExceptionAndValue(() => Linq.Average(srcNativeArray, SelectSelf<double>().Invoke));
        if (expected.Item1 != null)
            return; // Exceptions are not supported in Burst
        var actual = ExceptionAndValue(() => Blinq.ScheduleAverage(srcNativeArray, SelectSelf<double>()).Complete());
        srcNativeArray.Dispose();
        AssertAreEqual(expected, actual);
    }


}
